### ISSUE TITLE
Create slack channels for genesisblocktime.slack.com

### ISSUE THREAD

**Issue by guylepage3** [jrschupak/genesis#4]
Create all new necessary slack channels for genesisblocktime.slack.com

Using getbootstrap.slack.com as an example here's what i recommend:
- v1
- general
- help
- random
- frontend
- git

Thoughts?

**Comment by jrschupak** [comment]
Sounds good to me

**Comment by guylepage3** [comment]
@jrschupak are you taking the lead on this????????????????????????????????

**Comment by jrschupak** [comment]
@guylepage3 I answered that in the other issue. I just made the channels in genesis.slack.com

**Comment by guylepage3** [comment]
Answered something from here in another issue??? I really think we need to finish https://github.com/jrschupak/genesis/issues/2 so that we get on the same page here.

**Comment by guylepage3** [comment]
Complete and closing
